In [3]:
from datetime import date,timedelta 

import requests
import zipfile

In [60]:
d1 = date(2019,3,14)
d2 = date(2019,3,13)

delta = d2 - d1

for i in range(0,delta.days+1) :
    objectiveData = d1 + timedelta(i)
    if int(objectiveData.strftime("%w")) in [0,6]: continue
    d_day = format(objectiveData.day,'02d')
    d_month =format(objectiveData.month,'02d')
    d_year =objectiveData.year 
    d_monthName = objectiveData.strftime("%b").upper()
    try :
        url = r"https://www.nseindia.com/content/historical/EQUITIES/" + str(d_year) +r"/"+d_monthName+r'/cm'+d_day+d_monthName+str(d_year)+r"bhav.csv.zip"
        outputfile="C:\\Users\\69292\\Documents\\TEMP\\NSE\\" + str(d_year) +"_"+d_month+"_"+d_day+r".zip"
        print(url)
        r = requests.get(url)
        with open(outputfile, "wb") as code:
            code.write(r.content)
        
        zip_ref = zipfile.ZipFile(outputfile, 'r')
        zip_ref.extractall("C:\\Users\\69292\\Documents\\TEMP\\NSE\\")
        zip_ref.close()
    except:
        continue

In [6]:
import calendar

import datetime

def last_day_of_month(any_day):
    next_month = any_day.replace(day=28) + datetime.timedelta(days=4)  # this will never fail
    return next_month - datetime.timedelta(days=next_month.day)

def download_data(ourdate):
    d_day = format(ourdate.day,'02d')
    d_month =format(ourdate.month,'02d')
    d_year =ourdate.year 
    d_monthName = ourdate.strftime("%b").upper()
    try :
        
        #url = r"https://www.nseindia.com/content/historical/EQUITIES/" + str(d_year) +r"/"+d_monthName+r'/cm'+d_day+d_monthName+str(d_year)+r"bhav.csv.zip"
        
        url = r"https://www.nseindia.com/archives/equities/bhavcopy/pr/PR" + str(d_day) + d_month+str(d_year)[2:4]+r".zip"
        outputfile="C:\\Users\\69292\\Documents\\TEMP\\NSE\\" + str(d_year) +"_"+d_month+"_"+d_day+r".zip"
        print(url)
        r = requests.get(url)
        with open(outputfile, "wb") as code:
            code.write(r.content)
        
        zip_ref = zipfile.ZipFile(outputfile, 'r')
        zip_ref.extractall("C:\\Users\\69292\\Documents\\TEMP\\NSE\\")
        zip_ref.close()
        return True
    except :
        return False 
    
#https://www.nseindia.com/archives/equities/bhavcopy/pr/PR290110.zip
        



In [39]:
import numpy as np 

t=np.arange(30)

mat = t.reshape(2,3,5)

print (mat)

print(mat[:,1,:])

print("last : \n" ,mat[:,1:2,:])

print(mat[:,1,:].shape)
print(mat[:,:,:].shape)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
last : 
 [[[ 5  6  7  8  9]]

 [[20 21 22 23 24]]]
(2, 5)
(2, 3, 5)


In [46]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))
d.add(4)

print(d)

None
None
None
{0, 1, 2, 4}


In [4]:
d1= date(2001,1,1)
for i in range(2016,2018):
    for j in range(1,13):
        ourdate = last_day_of_month(date(i,j,1))
        while download_data(ourdate) == False :
            ourdate = ourdate - timedelta(1)
            print("Tryed with other date " ,ourdate)
        


https://www.nseindia.com/content/historical/EQUITIES/2016/JAN/cm31JAN2016bhav.csv.zip
Tryed with other date  2016-01-30
https://www.nseindia.com/content/historical/EQUITIES/2016/JAN/cm30JAN2016bhav.csv.zip
Tryed with other date  2016-01-29
https://www.nseindia.com/content/historical/EQUITIES/2016/JAN/cm29JAN2016bhav.csv.zip
https://www.nseindia.com/content/historical/EQUITIES/2016/FEB/cm29FEB2016bhav.csv.zip
https://www.nseindia.com/content/historical/EQUITIES/2016/MAR/cm31MAR2016bhav.csv.zip
https://www.nseindia.com/content/historical/EQUITIES/2016/APR/cm30APR2016bhav.csv.zip
Tryed with other date  2016-04-29
https://www.nseindia.com/content/historical/EQUITIES/2016/APR/cm29APR2016bhav.csv.zip
https://www.nseindia.com/content/historical/EQUITIES/2016/MAY/cm31MAY2016bhav.csv.zip
https://www.nseindia.com/content/historical/EQUITIES/2016/JUN/cm30JUN2016bhav.csv.zip
https://www.nseindia.com/content/historical/EQUITIES/2016/JUL/cm31JUL2016bhav.csv.zip
Tryed with other date  2016-07-30
http

In [3]:
print("hellow")

hellow
