In [2]:
# Numpy in Action

import numpy as np  #alias 


In [3]:
myPythonList = [ 1,2,3,4]

#lets convert list into numpy array | memory effciency and performence

numpy_array = np.array(myPythonList)

print(numpy_array)
print(type(numpy_array))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# Arrays of various Data Types

x = np.array([1,2,3,4])
print(x)
print(x.dtype)

y= np.array([1.0,2.0,3.0])
print(y)
print(y.dtype)

z= np.array([1,2],dtype=np.int64)
print(z)
print(z.dtype)

[1 2 3 4]
int32
[1. 2. 3.]
float64
[1 2]
int64


In [5]:
#How Numpy is Memory efficient !!

# we are going to create a list (python) and array(numpy) of size 1000 elements
# we are going to check the total memory occupancy of each list/array

import sys

python_list=range(1000) #range function generates numbers from 0 to n-1

numpy_array = np.arange(1000) # arange does the same work as range in python.

print("The Total Size Occupied by Python List ",len(python_list)*sys.getsizeof(1))
print("The Total size of NumPy Array",numpy_array.size * numpy_array.itemsize)
      
#numpy_array.size : return number of elements in array
#numpy_array.itemsize : returns size occuped by 1 element in numpy array



The Total Size Occupied by Python List  28000
The Total size of NumPy Array 4000


In [7]:
#Performence Factor in Numpy : output: in the milliseconds sense
# i am going to create two python list   and two numpy arrays...
# i am going to see the difference in time (time comparision) while adding the two list.

import time
SIZE=1000000

L1 = range(SIZE)
L2= range(SIZE)

A1=np.arange(SIZE)
A2=np.arange(SIZE)

start= time.time()# started the time tracking 

result = [(x+y) for x,y in zip(L1,L2)]

stop=time.time() # getting the current time after additions

print("List Took ",(stop-start)*1000," Milliseconds")

# Lets do time tracking for Numpy

start=time.time()

result= A1+A2

stop=time.time()

print("Numpy Took ",(stop-start)*1000," Milliseconds")


List Took  257.68589973449707  Milliseconds
Numpy Took  32.52220153808594  Milliseconds


In [6]:
#Generating random Numbers in numpy..

print(np.random.rand(2,6)) #it generates an array of given dimension and the numbers
#will be between 1 and 0

print(np.random.choice(['a','e','i','o','u'],size=10))

[[0.23259453 0.64120138 0.60924455 0.3466713  0.03955718 0.61565668]
 [0.96479348 0.05942821 0.12930189 0.39843198 0.10053156 0.3899177 ]]
['a' 'i' 'i' 'a' 'e' 'a' 'a' 'i' 'o' 'a']


In [8]:
#Shape of Arrays: it tells you about the demensionality of numpy ndarray 

a = np.array([1,2,3,4]) #its a 1d array
print(a)
print(a.shape) #what .shape does it return number of elements in 1 day array case only.

[1 2 3 4]
(4,)


In [9]:
#Creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])

"""
1 2 3 4
5 6 7 8
"""
print(b.shape) #shape makes sense..


(2, 4)


In [10]:
b = np.array([[1,2,3,4],[5,6,7,8]])

print("Shape of b is ",b.shape)

#reshape the array

b = b.reshape(4,2)
print("\n\n")
print(b)

print("shape ",b.shape)

#Flatten

b = b.flatten() # its bring all the values in 1D order
print("After flattening\n")
print(b)

# [[[2,3,4],[5,6,7]]]

Shape of b is  (2, 4)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape  (4, 2)
After flattening

[1 2 3 4 5 6 7 8]


In [11]:
#testing 

a =np.array([1,2,3,4,5])
print(type(a))

print(a.shape)

print(a[0],a[1],[2])

a[0]=5   # <-- if you change any indexvalue it is reflected in original array(referencing.)
print(a)

b= np.array([[1,2,3],[4,5,6]])

"""
1 2 3
4 5 6
"""
print(b[0,0],b[0,1],b[1,0])


<class 'numpy.ndarray'>
(5,)
1 2 [2]
[5 2 3 4 5]
1 2 4


In [ ]:
#Slicing in 2D Array

In [49]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.shape)
"""
1  2  3  4
5  6  7  8
9 10 11 12
"""

#Challenge is to retrieve the 1st(index) row

row_1= a[1,:] # a [ row_index : ColumnIndex]
print(row_1)

row_1_copy=a[1:2,:]  # [1 to n-1]
print(row_1_copy)

#print [2,6,10]

print(a[:,1])

#Pull [2,3,6,7]

print(a[:2,1:3]) 


(3, 4)
[5 6 7 8]
[[5 6 7 8]]
[ 2  6 10]
[[2 3]
 [6 7]]


In [57]:
#Mathematical Computations!!

mylist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

np_arr = np.array(mylist,dtype="float")

print(np_arr)

print("Mean value is ",np_arr.mean())
print("Max value is ",np_arr.max())
print("Min Value is ",np_arr.min())

#======================
print("Column wise min ",np.amin(np_arr,axis=0))
print("Row wise min ",np.amin(np_arr,axis=1))


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Mean value is  6.5
Max value is  12.0
Min Value is  1.0
Column wise min  [1. 2. 3. 4.]
Row wise min  [1. 5. 9.]


In [61]:
# maths with np array
x= np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

r1 = x+y
print(r1)

r2=x-y
r2=np.subtract(x,y)
print(r2)

r3=x*y
r3=np.multiply(x,y)
print(r3)

#Can you send me the divide in chat window..

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [65]:
#3d 

a = np.array([ [[1,2,3],[1,2,3]]  ])
print(a)
print(a.shape)

[[[1 2 3]
  [1 2 3]]]
(1, 2, 3)
